### ISSUE TITLE
Projects in nested directories?

### ISSUE THREAD

**Issue by tomekw** [arkwright/vim-whiplash#6]
Thank you for the library! 🙇‍♂️ 

The way I organize my projects is as follows:

```
~/depot/org_1/project_1
~/depot/org_1/project_2
~/depot/org_2/project_1
~/depot/org_2/project_2
```

That means simple

```
let g:WhiplashProjectsDir = `~/depot`
```

won't work.

Is there any workaround maybe? 🤔

**Comment by arkwright** [comment]
Sorry it took me so long to get back to you!

Good question! I work on monorepo projects with a similar structure. What I do as a workaround is to symlink the nested project folders into the `g:WhiplashProjectsDir` folder, e.g.:

```
ln -Fhs ~/depot/org_1/project_1 ~/my_projects/project_1
```
```
let g:WhiplashProjectsDir = `~/my_projects`
```

Hope that helps!

**Comment by tomekw** [comment]
No worries @arkwright :) We all have lives, hopefully ;)

Thanks, I would like to avoid symlinking 🤔 I will figure something out!
